title: Max Bikes West
email: maxkatzchristy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Max Bikes West and other directions.
baseurl: "/maxbikeswest" # the subpath of your site, e.g. /blog
url: "https://maxtkc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  maxtkc
timezone: America/New_York

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index
    - title: About
      url: /about

social:
    github: maxtkc
    email: maxkatzchristy@gmail.com
    linkedin: max-katz-christy

paginate_path: "page-:num/"
permalink: :title/

# Build settings
remote_theme: maxtkc/long-haul
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

collections:
  category:
    output: true
